sudo: false

language: node_js

node_js:
  - 6
  - 8

before_install:
  - npm install -g typescript@2.6.2

install:
  - npm install

script:
  - tsc
  - npm install -g mocha
  - npm test

notifications:
  email:  
  - viktor@carvic.si
